apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubucon-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubucon-demo
  template:
    metadata:
      labels:
        app: ubucon-demo
    spec:
      containers:
      - name: ubucon-demo
        image: localhost:32000/ubucon:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ubucon-service
spec:
  selector:
    app: ubucon-demo
  ports:
    - port: 5000
      targetPort: 5000
      # protocol: TCP
